### ISSUE TITLE
Not launching up

### ISSUE THREAD

**Issue by dev1523** [amanjeetsingh150/Algo-Explorer#4]
The app force closes as soon as i open it on my device.
My device is OPPO N3.
Rom-Rooted Color OS
Android Version-4.4.4

**Comment by amanjeetsingh150** [comment]
Hi @dev1523 ,
Sorry for replying late. I have fixed the bug for this android version. It was due to ResourceNotFoundException due to some drawables which I placed in drawable-v21 rather than drawabales due to which they only render on lollipop and above. You can now run and check the application
Thanks 👍  :)
